// This work is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0) https://creativecommons.org/licenses/by-nc-sa/4.0/ 
// © Trendoscope Pty Ltd, Trendoscope® 
// ░▒ 
// ▒▒▒ ▒▒ 
// ▒▒▒▒▒ ▒▒ 
// ▒▒▒▒▒▒▒░ ▒ ▒▒ 
// ▒▒▒▒▒▒ ▒ ▒▒ 
// ▓▒▒▒ ▒ ▒▒▒▒▒▒▒▒▒▒▒ 
// ▒▒▒▒▒▒▒▒▒▒▒ ▒ ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ 
// ▒ ▒ ░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░ 
// ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒ 
// ▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒ 
// ▒▒▒▒▒ ▒▒▒▒▒▒▒ 
// ▒▒▒▒▒▒▒▒▒ 
// ▒▒▒▒▒ ▒▒▒▒▒ 
// ░▒▒▒▒ ▒▒▒▒▓ 
// @version=6 
indicator("Earnings Snapshot [Trendoscope®]", "ES[Trendoscope®]", overlay = true, max_labels_count = 500) 
enum DisplayType 
    TEXT = "Text" 
    TOOLTIP = "Tooltip" 

hma = ta.hma(close, 200) 
history = input.int(5, 'History', minval=1, maxval=24, step=1, display = display.none) 
displayType = input.enum(DisplayType.TEXT, 'On Chart', inline='d', display = display.none) 
displaySize = input.string(size.normal, '', [size.huge, size.large, size.normal, size.small, size.tiny], 'Select display type and size', inline='d', display=display.none) 
displayAsTable = input.bool(true, 'Show Table', inline='t', display = display.none) 
displayAsTooltip = displayType == DisplayType.TOOLTIP 

type Earnings
    float actual
    float estimated
    float standardized
    chart.point date
    Earnings lastEarnings
    Earnings y2yEarnings
    Earnings y1Earnings
    int dir
    float priceBefore
    float priceAfter
    float futureEstimated
    int futureDate

earningsActual = request.earnings(syminfo.tickerid, earnings.actual,barmerge.gaps_on)
earningsEstimated = request.earnings(syminfo.tickerid, earnings.estimate,barmerge.gaps_on)
earningsStandardised = request.earnings(syminfo.tickerid, earnings.standardized ,barmerge.gaps_on)

var array<Earnings> earningsArray = array.new<Earnings>()

if(not na(earningsActual))
    Earnings lastEarnings = na
    if(earningsArray.size()>0)
        lastEarnings := earningsArray.first()
    lastEarnings.futureEstimated := earningsEstimated
    lastEarnings.futureDate := time
    y2yEarings = (earningsArray.size()>=4)? earningsArray.get(3) : na
    y1Earnings = (earningsArray.size()>=3)? earningsArray.get(2) : na
    Earnings currentEarnings = Earnings.new(earningsActual, earningsEstimated, earningsStandardised, chart.point.now(high) , lastEarnings, y2yEarings, y1Earnings, close>hma?1:-1, close[1], close)
    earningsArray.unshift(currentEarnings)

method growth(Earnings current, Earnings last)=>
    earningsGrowth = 100*(current.actual - last.actual)/math.abs(last.actual)
    priceGrowth = 100*(current.priceAfter - last.priceAfter)/math.abs(last.priceAfter)
    [earningsGrowth, priceGrowth]

if(barstate.islast)
    lastEarnings = earningsArray.first()
    lastEarnings.futureEstimated := earnings.future_eps
    lastEarnings.futureDate := earnings.future_time

    var dataTable = table.new(position.top_right, 6, earningsArray.size()+2, na, chart.fg_color, 1, chart.fg_color, 1)
    dataTable.cell(0, 0, 'Date', text_color=color.white, bgcolor=color.new(color.maroon, 50), text_formatting=text.format_bold)
    dataTable.cell(1, 0, 'Last', text_color=color.white, bgcolor=color.new(color.maroon, 50), text_formatting=text.format_bold)
    dataTable.cell(3, 0, 'Y2Y', text_color=color.white, bgcolor=color.new(color.maroon, 50), text_formatting=text.format_bold)
    dataTable.cell(5, 0, 'Future', text_color=color.white, bgcolor=color.new(color.maroon, 50), text_formatting=text.format_bold)
    dataTable.cell(1, 1, 'Earning', text_color=color.white, bgcolor=color.new(color.maroon, 50), text_formatting=text.format_bold)
    dataTable.cell(2, 1, 'Price', text_color=color.white, bgcolor=color.new(color.maroon, 50), text_formatting=text.format_bold)
    dataTable.cell(3, 1, 'Earning', text_color=color.white, bgcolor=color.new(color.maroon, 50), text_formatting=text.format_bold)
    dataTable.cell(4, 1, 'Price', text_color=color.white, bgcolor=color.new(color.maroon, 50), text_formatting=text.format_bold)
    dataTable.cell(5, 1, 'Earning', text_color=color.white, bgcolor=color.new(color.maroon, 50), text_formatting=text.format_bold)
    dataTable.merge_cells(0,0,0,1)
    dataTable.merge_cells(1,0,2,0)
    dataTable.merge_cells(3,0,4,0)

    for [index, earningData] in earningsArray
        if(index >= history)
            break
        data = ''
        score = 0
        dataTable.cell(0, index+2, str.format_time(earningData.date.time, "yyyy-MM-dd", syminfo.timezone), text_color=chart.fg_color, bgcolor=color.new(color.maroon, 50), text_formatting=text.format_bold)
        if(not na(earningData.lastEarnings))
            [earningsGrowth, priceGrowth] = earningData.growth(earningData.lastEarnings)
            earningsGrowthInfo = str.format('Earnings(Last) : {0} -> {1} ({2})', earningData.lastEarnings.actual, earningData.actual, str.tostring(earningsGrowth, format.percent))
            priceInfo = str.format('Price(Last) : {0} -> {1} ({2})', str.tostring(earningData.lastEarnings.priceAfter, format.mintick), str.tostring(nz(earningData.priceAfter, earningData.priceBefore), format.mintick), str.tostring(priceGrowth, format.percent))
            score += (earningsGrowth>0?1:earningsGrowth<0?-1:0)+ (priceGrowth>0?1:priceGrowth<0?-1:0)+ (earningsGrowth>priceGrowth?1:earningsGrowth<priceGrowth?-1:0)
            data+=earningsGrowthInfo+'\n'+ priceInfo+'\n'
            dataTable.cell(1, index+2, str.tostring(earningsGrowth, format.percent), text_color=chart.fg_color, bgcolor = color.new(earningsGrowth>0?color.lime:color.orange, 80))
            dataTable.cell(2, index+2, str.tostring(priceGrowth, format.percent), text_color=chart.fg_color, bgcolor = color.new(priceGrowth>0?color.lime:color.orange, 80))

        if(not na(earningData.y2yEarnings))
            [yEarningsGrowth, yPriceGrowth] = earningData.growth(earningData.y2yEarnings)
            yEarningsGrowthInfo = str.format('Earnings(Y2Y) : {0} -> {1} ({2})', earningData.y2yEarnings.actual, earningData.actual, str.tostring(yEarningsGrowth, format.percent))
            yPriceInfo = str.format('Price(Y2Y) : {0} -> {1} ({2})', str.tostring(earningData.y2yEarnings.priceAfter, format.mintick), str.tostring(nz(earningData.priceAfter, earningData.priceBefore), format.mintick), str.tostring(yPriceGrowth, format.percent))
            score += (yEarningsGrowth>0?1:yEarningsGrowth<0?-1:0)+ (yPriceGrowth>0?1:yPriceGrowth<0?-1:0)+ (yEarningsGrowth>yPriceGrowth?1:yEarningsGrowth<yPriceGrowth?-1:0)
            data+=yEarningsGrowthInfo+'\n'+ yPriceInfo+'\n'
            dataTable.cell(3, index+2, str.tostring(yEarningsGrowth, format.percent), text_color=chart.fg_color, bgcolor = color.new(yEarningsGrowth>0?color.lime:color.orange, 80))
            dataTable.cell(4, index+2, str.tostring(yPriceGrowth, format.percent), text_color=chart.fg_color, bgcolor = color.new(yPriceGrowth>0?color.lime:color.orange, 80))

        if(not na(earningData.futureEstimated))
            estimatedGrowth = 100*(earningData.futureEstimated - earningData.actual)/math.abs(earningData.actual)
            estimateInfo = str.format('Estimate : {0} -> {1} ({2})', earningData.actual, earningData.futureEstimated, str.tostring(estimatedGrowth, format.percent))
            score += (estimatedGrowth>0?1:estimatedGrowth<0?-1:0)
            data+=estimateInfo
            dataTable.cell(5, index+2, str.tostring(estimatedGrowth, format.percent), text_color=chart.fg_color, bgcolor = color.new(estimatedGrowth>0?color.lime:color.orange, 80))

        lblColor = color.from_gradient(score, -7, 7, color.red, color.green)
        label.new(earningData.date, displayAsTooltip? str.tostring(score):data, xloc.bar_time, earningData.dir>0?yloc.belowbar:yloc.abovebar, color.new(lblColor, 70), displayAsTooltip?label.style_text_outline:(earningData.dir>0?label.style_label_up:label.style_label_down), displayAsTooltip?lblColor: chart.fg_color, displaySize, text.align_left, displayAsTooltip? data: na, font.family_monospace)