// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Monk_Trading
//@version=5
indicator(shorttitle='Simple Profit Monk trading', title='Simple Profite', overlay=true)

BBperiod = input.int(defval=21, title='BB Period', minval=1)
BBdeviations = input.float(defval=1.00, title='BB Deviations', minval=0.1, step=0.05)
UseATRfilter = input(defval=true, title='ATR Filter')
ATRperiod = input.int(defval=5, title='ATR Period', minval=1)
hl = input(defval=false, title='Hide Labels')

BBUpper = ta.sma(close, BBperiod) + ta.stdev(close, BBperiod) * BBdeviations
BBLower = ta.sma(close, BBperiod) - ta.stdev(close, BBperiod) * BBdeviations

TrendLine = 0.0
iTrend = 0.0
buy = 0.0
sell = 0.0

BBSignal = close > BBUpper ? 1 : close < BBLower ? -1 : 0

if BBSignal == 1 and UseATRfilter == 1
    TrendLine := low - ta.atr(ATRperiod)
    if TrendLine < TrendLine[1]
        TrendLine := TrendLine[1]
        
if BBSignal == -1 and UseATRfilter == 1
    TrendLine := high + ta.atr(ATRperiod)
    if TrendLine > TrendLine[1]
        TrendLine := TrendLine[1]
        
if BBSignal == 0 and UseATRfilter == 1
    TrendLine := TrendLine[1]

if BBSignal == 1 and UseATRfilter == 0
    TrendLine := low
    if TrendLine < TrendLine[1]
        TrendLine := TrendLine[1]
        
if BBSignal == -1 and UseATRfilter == 0
    TrendLine := high
    if TrendLine > TrendLine[1]
        TrendLine := TrendLine[1]
        
if BBSignal == 0 and UseATRfilter == 0
    TrendLine := TrendLine[1]

iTrend := iTrend[1]
if TrendLine > TrendLine[1]
    iTrend := 1
if TrendLine < TrendLine[1]
    iTrend := -1

buy := iTrend[1] == -1 and iTrend == 1 ? 1 : na
sell := iTrend[1] == 1 and iTrend == -1 ? 1 : na

plot(TrendLine, color=iTrend > 0 ? color.blue : color.red, style=plot.style_line, linewidth=2, title='Trend Line', transp=0)

plotshape(buy == 1 and hl == false ? TrendLine - ta.atr(8) : na, text='🢁', style=shape.labelup, location=location.absolute, color=color.new(color.blue, 0), textcolor=color.new(color.white, 0), offset=0, size=size.auto)
plotshape(sell == 1 and hl == false ? TrendLine + ta.atr(8) : na, text='🢃', style=shape.labeldown, location=location.absolute, color=color.new(color.red, 0), textcolor=color.new(color.white, 0), offset=0, size=size.auto)

alertcondition(sell == 1, title='Sell', message='Sell')
alertcondition(buy == 1, title='Buy', message='Buy')
alertcondition(buy == 1 or sell == 1, title='Buy/Sell', message='Buy/Sell')
