// TASC Issue: March 2026
// Article: Trading Snapbacks In A Leveraged ETF
// One Percent A Week: A High-Probability
// Weekly Trading Strategy For TQQQ - Part 1
// Article By: Dion Kurczek
// Language: TradingView's Pine Script® v6
// Provided By: PineCoders, for tradingview.com
//@version=6
strategy(
    "TASC 2026.03 One Percent A Week", "1%/W", overlay = true,
    initial_capital = 1000,
    default_qty_type = strategy.percent_of_equity,
    default_qty_value = 10
    )

//#region 1. Observe the weekly open price on Monday.
var float wOpen = na
var float pt = na
bool newSession = dayofweek == dayofweek.monday and session.isfirstbar_regular
if newSession
    wOpen := open
//#endregion

//#region 2. Set limit buy at a 1% dip from Monday open.
float down1 = wOpen * 0.99
if newSession
    strategy.entry("Buy", strategy.long, limit = down1)
    pt := na
//#endregion

//#region 3. Once filled, set a 1% target on the next day.
bool newFill = ta.change(strategy.position_size) != 0
var bool sendPT = false
var bool beSent = false
if strategy.position_size > 0 and newFill
    sendPT := true
    beSent := false
if sendPT == true and session.isfirstbar_regular and not beSent
    pt := strategy.position_avg_price * 1.01
    strategy.exit("TP", "Buy", limit = pt)
    beSent := true
//#endregion
